// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oarsalroburqrapjkqar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hcnNhbHJvYnVycXJhcGprcWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODQxNjYsImV4cCI6MjA2Njk2MDE2Nn0.Pt_HLxT7AIUpI82FI1pT__Bf1FceGOpRA8ZMhQFdhVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});